openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/categories:
    get:
      summary: 'Get all categories'
      operationId: getAllCategories
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      name: electronics
                      created_at: '1 week ago'
                      updated_at: '1 week ago'
                    -
                      id: 2
                      name: jewelry
                      created_at: '1 week ago'
                      updated_at: '1 week ago'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        name: electronics
                        created_at: '1 week ago'
                        updated_at: '1 week ago'
                      -
                        id: 2
                        name: jewelry
                        created_at: '1 week ago'
                        updated_at: '1 week ago'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: electronics
                        created_at:
                          type: string
                          example: '1 week ago'
                        updated_at:
                          type: string
                          example: '1 week ago'
      tags:
        - 'all data'
      security: []
tags:
  -
    name: 'all data'
    description: ''
